server:
  port: 8081
spring:
  application:
    name: blog-service
  profiles:
    active: local
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:blog
      username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

feign:
  level:
    com.example.blog.client: DEBUG
  client:
    config:
      default:
        loggerLevel: FULL

kakao:
  key: 0883eb55f567df2ba44a0ea04f826a2c
  baseUrl: https://dapi.kakao.com
  blogSearchUrl: /v2/search/blog

naver:
  clientId: UPKYlH4XrYj9El4ukcJd
  clientSecret: HfygOL38xT
  baseUrl: https://openapi.naver.com
  blogSearchUrl: /v1/search/blog.json